# -*- coding: utf-8 -*-
"""FLP_GA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vwGCUcZz0poQmcZ9Nsatj2tx5BQaof26
"""

import math
import random
import matplotlib.pyplot as plt
import copy
import time

"""### 1. Classe que vai representar a instância"""

class Instance:
    def __init__(self):
        self.num_clients = 0
        self.num_facilities = 0
        self.p_max = 0
        self.clients = [] # Lista de dicts: {'id':, 'x':, 'y':, 'demand':}
        self.facilities = [] # Lista de dicts: {'id':, 'x':, 'y':, 'capacity':, 'cost':}
        self.dist_matrix = [] # Matriz [cliente][facilidade]

    def calc_euclidean_distance(self, c, f):
        return math.sqrt((c['x'] - f['x'])**2 + (c['y'] - f['y'])**2)

    def precompute_distances(self):
        # Pré-calcula distâncias para evitar contas repetidas no loop do GA
        self.dist_matrix = [[0.0] * self.num_facilities for _ in range(self.num_clients)]
        for i in range(self.num_clients):
            for j in range(self.num_facilities):
                dist = self.calc_euclidean_distance(self.clients[i], self.facilities[j])
                self.dist_matrix[i][j] = dist

"""### 2. Parser"""

def parse_file(file_path):
    instance = Instance()

    with open(file_path, 'r') as f:
        lines = f.readlines()

    mode = None

    # Dicionários temporários para montagem
    temp_cli_coords = {}
    temp_cli_demand = {}
    temp_fac_coords = {}
    temp_fac_cap = {}
    temp_fac_cost = {}

    for line in lines:
        line = line.strip()
        if not line: continue

        # Leitura dos Parâmetros Globais
        if line.startswith("# N_Clientes"):
            instance.num_clients = int(line.split("=")[1].strip())
        elif line.startswith("# N_Facilidades"):
            instance.num_facilities = int(line.split("=")[1].strip())
        elif line.startswith("# P ("):
            instance.p_max = int(line.split("=")[1].strip())

        # Detecção de Seções
        elif "Coordenadas dos Clientes" in line: mode = "cli_coord"
        elif "Demandas dos Clientes" in line: mode = "cli_dem"
        elif "Coordenadas das Facilidades" in line: mode = "fac_coord"
        elif "Capacidades das Facilidades" in line: mode = "fac_cap"
        elif "Custos Fixos" in line: mode = "fac_cost"
        elif "Matriz" in line: mode = "ignore" # Vamos recalcular para garantir precisão
        elif "SOLUÇÃO" in line: break # Para de ler se achar o gabarito no final

        # Leitura de Dados baseada no modo
        elif mode == "cli_coord" and line[0].isdigit():
            parts = line.split()
            if len(parts) >= 3:
                temp_cli_coords[int(parts[0])] = (float(parts[1]), float(parts[2]))

        elif mode == "cli_dem" and line[0].isdigit():
            parts = line.split()
            if len(parts) >= 2:
                temp_cli_demand[int(parts[0])] = float(parts[1])

        elif mode == "fac_coord" and line[0].isdigit():
            parts = line.split()
            if len(parts) >= 3:
                temp_fac_coords[int(parts[0])] = (float(parts[1]), float(parts[2]))

        elif mode == "fac_cap" and line[0].isdigit():
            parts = line.split()
            if len(parts) >= 2:
                temp_fac_cap[int(parts[0])] = float(parts[1])

        elif mode == "fac_cost" and line[0].isdigit():
            parts = line.split()
            if len(parts) >= 2:
                temp_fac_cost[int(parts[0])] = float(parts[1])

    # Consolidação dos dados nas listas da Instância
    for i in range(1, instance.num_clients + 1):
        instance.clients.append({
            'id': i,
            'x': temp_cli_coords[i][0],
            'y': temp_cli_coords[i][1],
            'demand': temp_cli_demand[i]
        })

    for i in range(1, instance.num_facilities + 1):
        instance.facilities.append({
            'id': i,
            'x': temp_fac_coords[i][0],
            'y': temp_fac_coords[i][1],
            'capacity': temp_fac_cap[i],
            'cost': temp_fac_cost[i]
        })

    instance.precompute_distances()
    print(f"Instância Carregada: {instance.num_facilities} Facilidades, {instance.num_clients} Clientes.")
    return instance

"""### 3. Algoritmo Genético"""
def calculate_fitness(chromosome, instance):
    open_facilities_indices = [i for i, gene in enumerate(chromosome) if gene == 1]

    if len(open_facilities_indices) == 0:
        return float('inf'), None, None
    if len(open_facilities_indices) > instance.p_max:
        return float('inf'), None, None

    total_fixed_cost = sum([instance.facilities[i]['cost'] for i in open_facilities_indices])
    total_transport_cost = 0.0

    remaining_capacity = {i: instance.facilities[i]['capacity'] for i in open_facilities_indices}
    client_assignment = [-1] * instance.num_clients

    # Atribuição por demanda decrescente, tie-break aleatório
    clients_idx = list(range(instance.num_clients))
    clients_idx.sort(key=lambda ci: instance.clients[ci]['demand'], reverse=True)
    random.shuffle(clients_idx)

    unmet_clients = 0

    for c_idx in clients_idx:
        client = instance.clients[c_idx]
        options = []
        for f_idx in open_facilities_indices:
            dist = instance.dist_matrix[c_idx][f_idx]
            options.append((dist, f_idx))
        options.sort(key=lambda x: x[0])

        assigned = False
        for dist, f_idx in options:
            if remaining_capacity[f_idx] >= client['demand']:
                remaining_capacity[f_idx] -= client['demand']
                # NOTE: transporte = distância (sem multiplicar pela demanda)
                total_transport_cost += dist
                client_assignment[c_idx] = instance.facilities[f_idx]['id']
                assigned = True
                break
        if not assigned:
            unmet_clients += 1

    # penalidade clássica (muito alta) por cliente não atendido
    penalty_per_unmet_client = 10000.0
    penalty_cost = penalty_per_unmet_client * unmet_clients

    total_cost = total_fixed_cost + total_transport_cost + penalty_cost
    return total_cost, client_assignment, open_facilities_indices


def genetic_algorithm(instance, pop_size=100, generations=300, mutation_rate=0.05):
    """
    Substituição do GA por um Iterated Local Search (ILS) + VND implementado inline.
    Mantive a assinatura para compatibilidade com o restante do código.
    Retorna: best_cost, best_solution, best_assignment, history
    """
    random.seed(time.time()) # usa seed do sistema

    # Ajuste dinâmico de iterações (interpreto 'generations' como máximo de iterações de ILS)
    max_iters = generations
    if instance.num_facilities >= 50:
        max_iters = max(max_iters, 500)
        pop_size = max(pop_size, 200)
        print(f"Instância grande detectada. Ajustando iterações para {max_iters} e pop_size para {pop_size}")

    def make_random_chrom():
        chrom = [0] * instance.num_facilities
        num_to_open = random.randint(1, instance.p_max)
        for idx in random.sample(range(instance.num_facilities), num_to_open):
            chrom[idx] = 1
        return chrom

    # Históricos e melhores
    best_solution = None
    best_cost = float('inf')
    best_assignment = None
    history = []

    # --- Construções iniciais: mistura de soluções aleatórias e heurísticas simples ---
    initial_pool = []
    # Gera algumas soluções aleatórias
    n_random_inits = min(20, pop_size)
    for _ in range(n_random_inits):
        initial_pool.append(make_random_chrom())

    # Gera algumas soluções heurísticas: abre facilidades com melhor razão (capacidade / custo)
    # sem criar nova função de topo: fazemos inline
    ratio_list = []
    for i, f in enumerate(instance.facilities):
        cost = f['cost'] if f['cost'] > 0 else 1e-6
        ratio = f['capacity'] / cost
        ratio_list.append((ratio, i))
    ratio_list.sort(reverse=True)
    # criar variantes com os top-k facilities
    for k in range(1, min(instance.p_max, max(1, instance.num_facilities//10)) + 1):
        chrom = [0] * instance.num_facilities
        for _, idx in ratio_list[:k]:
            chrom[idx] = 1
        initial_pool.append(chrom)

    # Garantir um número razoável de inícios
    if len(initial_pool) < 30:
        for _ in range(30 - len(initial_pool)):
            initial_pool.append(make_random_chrom())

    print(f"Preparando ILS+VND com {len(initial_pool)} soluções iniciais (pool).")

    # --- Função inline: aplica VND (busca local best-improvement) na solução atual ---
    # Não é uma nova função de topo — é apenas um loop inline reutilizável.
    def vnd_improve(chrom):
        # retorna melhor (cost, chrom, assignment)
        current = chrom[:]
        current_cost, current_assign, _ = calculate_fitness(current, instance)
        improved = True
        #vnd_max_iter = 100  # número máximo de rodadas de busca local
        #vnd_iter = 0

        # VND alterna entre neighborhoods: 1) flip, 2) swap
        while improved:
            improved = False
            # --- Neighborhood 1: best flip (abrir/fechar um bit) ---
            best_local_cost = current_cost
            best_local_sol = None
            best_local_assign = None
            for i in range(instance.num_facilities):
                # tenta flip
                child = current[:]
                child[i] = 1 - child[i]
                # validade: não deixa tudo 0 e não excede p_max
                if sum(child) == 0:
                    continue
                if sum(child) > instance.p_max:
                    continue
                cost_c, assign_c, _ = calculate_fitness(child, instance)
                if cost_c < best_local_cost:
                    best_local_cost = cost_c
                    best_local_sol = child
                    best_local_assign = assign_c
            if best_local_sol is not None:
                current = best_local_sol
                current_cost = best_local_cost
                current_assign = best_local_assign
                improved = True
                continue  # recomeça VND (primeira vizinhança novamente)

            # --- Neighborhood 2: best swap (fechar i aberto e abrir j fechado) ---
            best_local_cost = current_cost
            best_local_sol = None
            best_local_assign = None
            open_indices = [i for i, g in enumerate(current) if g == 1]
            closed_indices = [i for i, g in enumerate(current) if g == 0]
            # Se não houver ambos, pula
            if open_indices and closed_indices:
                # explorar pares (poderia ser O(n^2) — limitamos para desempenho: examinamos amostra quando grande)
                max_pairs_check = 2000
                pairs = []
                if len(open_indices) * len(closed_indices) <= max_pairs_check:
                    for oi in open_indices:
                        for cj in closed_indices:
                            pairs.append((oi, cj))
                else:
                    # amostragem aleatória de pares para manter a busca rápida em instâncias grandes
                    for _ in range(max_pairs_check):
                        oi = random.choice(open_indices)
                        cj = random.choice(closed_indices)
                        pairs.append((oi, cj))
                # avaliar pairs
                for oi, cj in pairs:
                    child = current[:]
                    child[oi] = 0
                    child[cj] = 1
                    # garantia: não excede p_max (troca mantem soma igual)
                    cost_c, assign_c, _ = calculate_fitness(child, instance)
                    if cost_c < best_local_cost:
                        best_local_cost = cost_c
                        best_local_sol = child
                        best_local_assign = assign_c
            if best_local_sol is not None:
                current = best_local_sol
                current_cost = best_local_cost
                current_assign = best_local_assign
                improved = True
                continue

            # se chegou aqui, não melhorou em nenhuma vizinhança -> convergiu
        return current_cost, current, current_assign

    # --- ILS principal: para cada solução inicial tenta intensificar com VND e perturbar para escapar ---
    iter_count = 0
    no_improve_iters = 0
    max_no_improve = max(50, max_iters // 10)
    # Limite de iterações totais
    while iter_count < max_iters:
        # Escolher uma solução inicial do pool (rotaciona)
        init_chrom = initial_pool[iter_count % len(initial_pool)][:]
        # Se for tudo zero (por engano), cria aleatória
        if sum(init_chrom) == 0:
            init_chrom = make_random_chrom()

        # Primeiro: tornar válida se excede p_max (fechar aleatoriamente extras)
        if sum(init_chrom) > instance.p_max:
            ones = [i for i, g in enumerate(init_chrom) if g == 1]
            to_remove = random.sample(ones, sum(init_chrom) - instance.p_max)
            for i in to_remove:
                init_chrom[i] = 0

        # Aplicar VND local search
        cur_cost, cur_sol, cur_assign = vnd_improve(init_chrom)

        # Atualiza global se melhor
        if cur_cost < best_cost:
            best_cost = cur_cost
            best_solution = cur_sol[:]
            best_assignment = cur_assign[:]
            no_improve_iters = 0
            print(f"Iter {iter_count}: Novo melhor custo global = {best_cost:.2f}")
        else:
            no_improve_iters += 1

        history.append(best_cost)
        iter_count += 1

        # Se sem melhora por muito tempo, aplica perturbação na solução corrente e re-aplica VND
        if no_improve_iters >= max_no_improve:
            # Perturbação forte: flip de K bits (K cresce com estagnação)
            K = min( max(1, instance.num_facilities // 20), 1 + no_improve_iters // 20 )
            # start from best solution found so far to intensify em torno do melhor
            base = best_solution[:] if best_solution is not None else make_random_chrom()
            pert = base[:]
            # escolha K índices (preferir fechar ou abrir com prob)
            indices = list(range(instance.num_facilities))
            for idx in random.sample(indices, min(K, instance.num_facilities)):
                pert[idx] = 1 - pert[idx]
            # corrigir p_max e zero
            if sum(pert) == 0:
                pert[random.randint(0, instance.num_facilities-1)] = 1
            if sum(pert) > instance.p_max:
                ones = [i for i, g in enumerate(pert) if g == 1]
                to_remove = random.sample(ones, sum(pert) - instance.p_max)
                for i in to_remove:
                    pert[i] = 0
            # aplicar VND na solução perturbada
            cur_cost2, cur_sol2, cur_assign2 = vnd_improve(pert)
            if cur_cost2 < best_cost:
                best_cost = cur_cost2
                best_solution = cur_sol2[:]
                best_assignment = cur_assign2[:]
                no_improve_iters = 0
                print(f"Iter {iter_count}: Melhor após perturbação = {best_cost:.2f}")
            history.append(best_cost)
            iter_count += 1
            # se iter_count exceder, break naturalmente

    # final fallback se nada válido encontrado
    if best_solution is None:
        # gera solução aleatória válida e retorna seu custo
        sol = make_random_chrom()
        cost, assign, _ = calculate_fitness(sol, instance)
        best_solution = sol
        best_cost = cost
        best_assignment = assign

    return best_cost, best_solution, best_assignment, history

"""### 4. Plotagem"""

def plot_solution(instance, open_facilities_mask, assignments, total_cost):
    plt.figure(figsize=(10, 8))

    # Plota Clientes e linhas de conexão
    # Cores para cada facilidade para diferenciar os clusters
    colors = plt.cm.get_cmap('tab20', instance.num_facilities)

    # Desenhar linhas primeiro (para ficarem no fundo)
    for c_idx, fac_id_assigned in enumerate(assignments):
        if fac_id_assigned != -1:
            client = instance.clients[c_idx]
            # Achar a facilidade correspondente (lembrando que fac_id é 1-based)
            facility = next(f for f in instance.facilities if f['id'] == fac_id_assigned)

            plt.plot([client['x'], facility['x']], [client['y'], facility['y']],
                     color='lightgray', linewidth=0.5, zorder=1)

    # Plota Clientes
    for c in instance.clients:
        plt.scatter(c['x'], c['y'], c='blue', s=20, alpha=0.6, zorder=2, label='Cliente' if c['id']==1 else "")

    # Plota Facilidades
    legend_added_open = False
    legend_added_closed = False

    for i, f in enumerate(instance.facilities):
        is_open = open_facilities_mask[i] == 1
        if is_open:
            plt.scatter(f['x'], f['y'], c='red', marker='D', s=100, edgecolors='black', zorder=3,
                        label='Facilidade Aberta' if not legend_added_open else "")
            # Adiciona ID da facilidade
            plt.text(f['x'], f['y']+2, str(f['id']), fontsize=9, fontweight='bold', color='darkred')
            legend_added_open = True
        else:
            plt.scatter(f['x'], f['y'], c='gray', marker='x', s=50, alpha=0.5, zorder=2,
                        label='Facilidade Fechada' if not legend_added_closed else "")
            legend_added_closed = True

    plt.title(f"Solução FLP - Custo Total: {total_cost:.2f}")
    plt.xlabel("Coordenada X")
    plt.ylabel("Coordenada Y")
    plt.legend(loc='upper right')
    plt.grid(True, linestyle='--', alpha=0.5)

    # Salva ou mostra
    plt.tight_layout()
    plt.show()

"""### 5. Execução do código"""

ARQUIVO_ALVO = "Instancia_FLP_3.txt"

# 1. Ler Arquivo
print(f"--- Lendo {ARQUIVO_ALVO} ---")
instancia = parse_file(ARQUIVO_ALVO)

# --- Resetar variáveis antigas ---
history = None
solucao = None
alocacoes = None
custo = None
best_solution = None
best_assignment = None
best_cost = None

# 2. Executar GA
start_time = time.time()
custo, solucao, alocacoes, hist = genetic_algorithm(instancia)
end_time = time.time()

# 3. Mostrar Resultados
print("\n" + "="*40)
print("RESULTADO FINAL")
print("="*40)
print(f"Tempo de Execução: {end_time - start_time:.2f} segundos")
print(f"Melhor Custo Encontrado: {custo:.2f}")

facilidades_abertas_ids = [instancia.facilities[i]['id'] for i, bit in enumerate(solucao) if bit == 1]
print(f"Facilidades Abertas ({len(facilidades_abertas_ids)}): {facilidades_abertas_ids}")

# Plota gráfico de convergência
plt.figure()
plt.plot(hist)
plt.title("Convergência do Algoritmo Genético")
plt.xlabel("Geração")
plt.ylabel("Custo (Fitness)")
plt.show()
# 4. Plotar Mapa da Solução
plot_solution(instancia, solucao, alocacoes, custo)